services:
    test:
        build:
            context: "."
            dockerfile: "Dockerfile"
        restart: "no"
        volumes:
            - .:/app  # Mount your script directory
        working_dir: /app/tests   # Set working directory
        command: ../lib/bashunit --verbose ./unit