#----------------------------------------------------------
# This file is part of the gitlab-arm64 project.
#
# (c) Festim Kolgeci <festim.kolgei@pm.me>
#
# For complete copyright and license details, please refer
# to the LICENSE file distributed with this source code.
#----------------------------------------------------------

name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      gitlab_release:
        type: string
        description: "GitLab Release Docker-Tag (e.g. 17.6.1-ce.0)"
        required: true
      include_major_minor_tag:
        type: boolean
        description: "Update 'major.minor' tag (e.g. 17.6-ce)"
        required: false
        default: false
      include_major_tag:
        type: boolean
        description: "Update 'major' tag (e.g. 17-ce)"
        required: false
        default: false
      include_latest_tags:
        type: boolean
        description: "Only for newest release 'edition' (e.g. ce), and 'latest'"
        required: false
        default: false
      use_gitlab_official_arm64_image:
        type: boolean
        description: "Use GitLabs official arm64 image since version 18.1"
        required: false
        default: false


jobs:
  call-build-workflow:
    if: ${{ github.repository_owner == 'feskol' && github.ref == 'refs/heads/main' }} # Only on the main branch and exclude forked repositories
    uses: ./.github/workflows/_shared-build.yml
    secrets: inherit
    with:
      gitlab_release: ${{ github.event.inputs.gitlab_release }}
      include_major_minor_tag: ${{ fromJson(github.event.inputs.include_major_minor_tag) }}
      include_major_tag: ${{ fromJson(github.event.inputs.include_major_tag) }}
      include_latest_tags: ${{ fromJson(github.event.inputs.include_latest_tags) }}
      use_gitlab_official_arm64_image: ${{ fromJson(github.event.inputs.use_gitlab_official_arm64_image) }}
      is_test: false