name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      gitlab_release:
        description: "GitLab Release (e.g., 17.6.1+ce.0)"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: docker login to docker.io
        uses: docker/login-action@v2
        # Only builds on the main branch will trigger the push, and forked repositories are excluded
        if: github.repository_owner == 'feskol' && github.ref == 'refs/heads/main'
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup binfmt-support
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Download GitLab Build Files
        run: |
          GITLAB_RELEASE=${{ github.event.inputs.gitlab_release }}
          mkdir -p build
          curl -sL "https://gitlab.com/gitlab-org/omnibus-gitlab/-/archive/${GITLAB_RELEASE}/omnibus-gitlab-${GITLAB_RELEASE}.tar.gz" | tar xz --strip-components=2 -C build "omnibus-gitlab-${GITLAB_RELEASE}/docker"

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v3
        with:
          context: build/docker
          # Only builds on the main branch will trigger the push, and forked repositories are excluded
          push: ${{ github.repository_owner == 'feskol' && github.ref == 'refs/heads/main' }}
          tags: ${{ github.event.inputs.gitlab_release }}
          platforms: linux/arm64
          # Disable provenance generation to resolve issue #82
          provenance: false
          build-args: |
            TARGETARCH=arm64

      - name: Clean Up
        run: |
          docker buildx rm
          rm -rf build