#----------------------------------------------------------
# This file is part of the gitlab-arm64 project.
#
# (c) Festim Kolgeci <festim.kolgei@pm.me>
#
# For complete copyright and license details, please refer
# to the LICENSE file distributed with this source code.
#----------------------------------------------------------

name: Build Docker Image

on:
  workflow_call:
    inputs:
      gitlab_release:
        type: string
        description: "GitLab Release Docker-Tag (e.g. 17.6.1-ce.0)"
        required: true
      include_major_minor_tag:
        type: boolean
        description: "Update 'major.minor' tag (e.g. 17.6-ce)"
        required: false
        default: false
      include_major_tag:
        type: boolean
        description: "Update 'major' tag (e.g. 17-ce)"
        required: false
        default: false
      include_latest_tags:
        type: boolean
        description: "Only for newest release 'edition' (e.g. ce), and 'latest'"
        required: false
        default: false
      is_test:
        type: boolean
        description: "Enable testing mode"
        required: false
        default: false
      run_docker_image_test:
        type: boolean
        description: "Build Docker images and run tests"
        required: false
        default: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Permissions
        # make all scripts in scripts/workflows/build executable
        run: chmod +x ./scripts/workflows/build/*.sh

      - name: Validate Input "gitlab_release"
        env:
          INPUT_GITLAB_RELEASE: ${{ inputs.gitlab_release }}
        run: ./scripts/workflows/build/validate_input_gitlab_release.sh

      - name: Extract GitLab Edition
        env:
          INPUT_GITLAB_RELEASE: ${{ inputs.gitlab_release }}
        run: ./scripts/workflows/build/extract_gitlab_edition_suffix.sh
        # GITHUB_ENV: GITLAB_EDITION_SUFFIX

      - name: Generate Tags
        env:
          INPUT_GITLAB_RELEASE: ${{ inputs.gitlab_release }}
          INPUT_INCLUDE_LATEST_TAGS: ${{ inputs.include_latest_tags }}
          INPUT_INCLUDE_MAJOR_TAG: ${{ inputs.include_major_tag }}
          INPUT_INCLUDE_MAJOR_MINOR_TAG: ${{ inputs.include_major_minor_tag }}
          GITLAB_EDITION_SUFFIX: ${{ env.GITLAB_EDITION_SUFFIX }}
        run: ./scripts/workflows/build/generate_tags.sh
        # GITHUB_ENV: GENERATED_TAGS

      - name: Generate Docker tags
        env:
          INPUT_GITLAB_RELEASE: ${{ inputs.gitlab_release }}
          GENERATED_TAGS: ${{ env.GENERATED_TAGS }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        run: ./scripts/workflows/build/generate_docker_tags.sh
        # GITHUB_ENV: DOCKERHUB_PUSH_TAGS
        # GITHUB_ENV: DOCKERHUB_PUSH_ORIGINAL_TAG

      - name: Setup GitLab build files
        env:
          INPUT_GITLAB_RELEASE: ${{ inputs.gitlab_release }}
          GITLAB_EDITION_SUFFIX: ${{ env.GITLAB_EDITION_SUFFIX }}
        run: ./scripts/workflows/build/setup_build_files.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: inputs.is_test == false
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export ARM64 image
        uses: docker/build-push-action@v6
        if: inputs.run_docker_image_test == true
        with:
          context: build
          load: true
          push: false
          tags: ${{ env.DOCKERHUB_PUSH_TAGS }}
          platforms: linux/arm64
          provenance: false
          build-args: |
            TARGETARCH=arm64

      - name: Test Docker Image
        if: inputs.run_docker_image_test == true
        run: |
          docker run -d --name  test-container --platform linux/arm64 ${{ env.DOCKERHUB_PUSH_ORIGINAL_TAG }}
          
          start_time=$(date +%s) # Record the start time
          
          # Wait for health status
          for i in {1..100}; do
            current_time=$(date +%s) # Current time in seconds
            elapsed_time=$((current_time - start_time)) # Calculate elapsed time
          
            status=$(docker inspect --format='{{.State.Health.Status}}' test-container)
            if [ "$status" = "healthy" ]; then
              echo "[$elapsed_time seconds elapsed] Container is healthy!"
              break
            elif [ "$status" = "unhealthy" ]; then
              echo "[$elapsed_time seconds elapsed] Container is unhealthy!"
              break
            else
              echo "[$elapsed_time seconds elapsed] Current status: $status"
            fi
            sleep 5
          done
          
          # Stop and clean up
          docker stop test-container && docker rm test-container

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v6
        if: inputs.is_test == false
        with:
          context: build
          push: true
          tags: ${{ env.DOCKERHUB_PUSH_TAGS }}
          platforms: linux/arm64
          provenance: false
          build-args: |
            TARGETARCH=arm64

      - name: Clean Up
        run: |
          docker buildx rm
          rm -rf build