#----------------------------------------------------------
# This file is part of the gitlab-arm64 project.
#
# (c) Festim Kolgeci <festim.kolgei@pm.me>
#
# For complete copyright and license details, please refer
# to the LICENSE file distributed with this source code.
#----------------------------------------------------------

on:
  workflow_dispatch:

jobs:
  import-docker-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Fetch Docker tags
        run: |
          # Fetch own docker tags
          feskol_url="https://hub.docker.com/v2/repositories/feskol/gitlab/tags?page_size=100"
          
          while [[ -n "$feskol_url" ]]; do
            # Fetch data from the current URL
            response=$(curl -s "$feskol_url")
            
            # Extract tags and append to file
            echo "$response" | jq -r '.results[].name' >> own_tags.txt
            
            # Get the next page URL (or empty if no next page)
            feskol_url=$(echo "$response" | jq -r '.next // empty')
          done
          
          cat own_tags.txt

      - name: Docker login GitHubs container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy existing dockerhub images to github container registry
        run: |
          while IFS= read -r tag; do
            docker_image=docker.io/feskol/gitlab:$tag
            ghcr_image=ghcr.io/${{ github.repository_owner }}/gitlab:$tag
          
            echo "$docker_image"
            echo "$ghcr_image"
          
            docker buildx imagetools create --tag "$ghcr_image" "$docker_image"  
          done < "own_tags.txt"