#----------------------------------------------------------
# This file is part of the gitlab-arm64 project.
#
# (c) Festim Kolgeci <festim.kolgei@pm.me>
#
# For complete copyright and license details, please refer
# to the LICENSE file distributed with this source code.
#----------------------------------------------------------

name: GitLab Release Checker

on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  call-snycversion-workflow:
    if: ${{ github.repository_owner == 'feskol' && github.ref == 'refs/heads/main' }} # Only on the main branch and exclude forked repositories
    uses: ./.github/workflows/_shared-syncversion.yml
    secrets: inherit
    with:
      is_test: false